# Adjust Parameters

## Load packages
```{r load packages}
library(deSolve)
library(reshape2)
library(ggplot2)
```

## Set parameters
```{r set parameters}
# load parameters from csv file.

# load alpha, lambda, mu, p
vars <- read.csv("./vars_calc.csv")

# load adjusted p
adjusted_p <- read.csv("./adjusted_p.csv")

# set initial values
total_initial_values_v <- data.frame(
    age_groups = c("00_17", "18_64", "65_84", "85_"),
    S = c(10116999, 36138999, 9315999, 1456999),
    I = c(1, 1, 1, 1),
    R = c(0, 0, 0, 0),
    H = c(0, 0, 0, 0),
    V = c(0, 0, 0, 0),
    D = c(0, 0, 0, 0)
)

# define function to get the value of parameter
get_specific_parameter <- function(phase, age_group, parameter) {
    if (parameter == "q") {
        if (phase == "phase2") {
            0.79
        } else if (phase == "phase3") {
            0.67
        } else if (phase == "phase4") {
            0.62
        } else {
            NA
        }
    } else {
        vars[
            vars$phase == phase &
                vars$age_group == age_group &
                vars$var_name == parameter,
            "mean"
        ]
    }
}

get_parameters <- function(phase, age_group, coverage) {
    c(
        gamma1 = 1 / 14,
        gamma2 = 1 / 21,
        sigma = 1 / 90,
        lambda = get_specific_parameter(phase, age_group, "lambda"),
        alpha = get_specific_parameter(phase, age_group, "alpha"),
        mu = get_specific_parameter(phase, age_group, "mu"),
        p = ifelse(
            coverage == "current",
            get_specific_parameter(phase, age_group, "p"),
            get_adjusted_p(coverage, age_group)
        ),
        q = get_specific_parameter(phase, age_group, "q")
    )
}

# define function to get the time sequence
get_times <- function(phase) {
    if (phase == "phase1") {
        seq(from = 1, to = 313, by = 1)
    } else if (phase == "phase2") {
        seq(from = 314, to = 473, by = 1)
    } else if (phase == "phase3") {
        seq(from = 474, to = 667, by = 1)
    } else if (phase == "phase4") {
        seq(from = 668, to = 932, by = 1)
    }
}

# define function to get the initial values
get_initial_values_v <- function(age_group) {
    c(
        S = total_initial_values_v[
            total_initial_values_v$age_groups == age_group,
            "S"
        ],
        I = total_initial_values_v[
            total_initial_values_v$age_groups == age_group,
            "I"
        ],
        R = total_initial_values_v[
            total_initial_values_v$age_groups == age_group,
            "R"
        ],
        H = total_initial_values_v[
            total_initial_values_v$age_groups == age_group,
            "H"
        ],
        V = total_initial_values_v[
            total_initial_values_v$age_groups == age_group,
            "V"
        ],
        D = total_initial_values_v[
            total_initial_values_v$age_groups == age_group,
            "D"
        ]
    )
}

# define function to get the adjusted value of p
get_adjusted_p <- function(coverage, age_group) {
    adjusted_p[
        adjusted_p$coverage == coverage,
        paste("p", age_group, sep = "")
    ]
}


# define function to the x-axis values
get_x_axis_values <- function(times) {
    as.Date("2020-1-30") + times
}
```

## Define model function 
```{r define model function}
# SIR MODEL DEFINE FUNCTION:

# The model function takes as input arguments
sir_model <- function(is_first_phase) {
    function(time, state, parameters) {
        # tell R to unpack variable names from the state and parameters inputs
        with(as.list(c(state, parameters)), {
            # The differential equations
            if (is_first_phase) {
                dI <- lambda * S - alpha * I - gamma1 * I
                dS <- -lambda * S + sigma * R
                dV <- 0
            } else {
                dS <- -lambda * S - p * S + sigma * R
                dI <- (1 - q) * lambda * V + lambda * S - alpha * I - gamma1 * I
                dV <- -(1 - q) * lambda * V + p * S
            }
            dR <- gamma1 * I + gamma2 * H - sigma * R
            dH <- alpha * I - mu * H - gamma2 * H
            dD <- H * mu
            return(list(c(dS, dI, dR, dH, dV, dD)))
        })
    }
}

# SIR MODEL SOLVE FUNCTION

sir_solve <- function(times, initial_values, parameters, is_first_phase) {
    # Solving the differential equations using the ode integration algorithm
    as.data.frame(ode(
        y = initial_values,
        times = times,
        func = sir_model(is_first_phase),
        parms = parameters
    ))
}

age_group_solve <- function(age_group, coverage = "current") {
    # get the initial environment
    initial_values <- get_initial_values_v(age_group)

    # solve the output of sir model
    phases <- c(
        "phase1",
        "phase2"
        # "phase3",
        # "phase4"
    )
    output <- c()
    for (phase in phases) {
        parameters <- get_parameters(phase, age_group, coverage)
        times <- get_times(phase)
        is_first_phase <- phase == "phase1"
        output_phase <- sir_solve(
            times,
            initial_values,
            parameters,
            is_first_phase
        )
        # update initial values
        initial_values <- c(
            S = output_phase[nrow(output_phase), "S"],
            I = output_phase[nrow(output_phase), "I"],
            R = output_phase[nrow(output_phase), "R"],
            H = output_phase[nrow(output_phase), "H"],
            V = output_phase[nrow(output_phase), "V"],
            D = output_phase[nrow(output_phase), "D"]
        )

        # merge output
        output <- rbind(output, output_phase)
    }
    output
}

# age_group_solve("00_17", "0%"
```

## Adjust the value of p
```{r adjust p}
coverage_list <- c(
    "current",
    "20%",
    "40%",
    "60%",
    "80%"
)

age_groups <- c(
    "00_17",
    "18_64",
    "65_84",
    "85_"
)

```

```{r}
# plot
library(ggplot2)
library(cowplot)

plot_list <- list()
cnt <- 1

index_map <- c(
    I = "infections",
    H = "hospitalisations",
    D = "deaths",
    R = "recovery"
)

for (index in c("I", "H", "D", "R")) {
    for (coverage in coverage_list) {
        times <- get_times("phase2")
        output_coverage <- c(times)
        for (age_group in age_groups) {
            output <- age_group_solve(age_group, coverage)
            output <- output[times, index]
            output_coverage <- cbind(output_coverage, output)
        }

        plot_times <- get_x_axis_values(times)
        colnames(output_coverage) <- c("times", age_groups)
        output_long <- melt(as.data.frame(output_coverage), id = "times")

        plot_temp <- ggplot(
            data = output_long, # specify object containing data to plot
            aes(x = times, y = value, colour = variable, group = variable)
        ) + # assign columns to axes and groupss
            geom_line() + # represent data as lines
            xlab("Time (days)") + # add label for x axis
            ylab("Values of the numbers") + # add label for y axis
            labs(colour = "Compartment") + # add legend title
            ggtitle(
                sprintf(
                    "Numbers of %s in %s coverages",
                    index_map[index], coverage
                )
            ) + # add title
            theme(plot.title = element_text(hjust = 0.5))

        plot_list[[cnt]] <- plot_temp
        cnt <- cnt + 1
    }
}

for (p in plot_list) {
    print(p)
}
```
## Adjust the value of p
```{r adjust p}
vaccination_list <- c(
    "1",
    "2",
    "3",
    "4",
    "5",
    "6"
)
age_groups <- c(
    "00_17",
    "18_64",
    "65_84",
    "85_"
)
```

```{r}
# plot
library(ggplot2)
library(cowplot)

plot_list <- list()
cnt <- 1

index_map <- c(
    I = "infections",
    H = "hospitalisations",
    D = "deaths",
    R = "recovery"
)

for (index in c("I", "H", "D", "R")) {
    for (vaccination in vaccination_list) {
        times <- get_times("phase2")
        output_vaccination <- c(times)
        for (age_group in age_groups) {
            output <- age_group_solve(age_group, vaccination)
            output <- output[times, index]
            output_vaccination <- cbind(output_vaccination, output)
        }

        plot_times <- get_x_axis_values(times)
        colnames(output_vaccination) <- c("times", age_groups)
        output_long <- melt(as.data.frame(output_vaccination), id = "times")

        plot_temp <- ggplot(
            data = output_long, # specify object containing data to plot
            aes(x = times, y = value, colour = variable, group = variable)
        ) + # assign columns to axes and groups
            geom_line() + # represent data as lines
            xlab("Time (days)") + # add label for x axis
            ylab("Values of the numbers") + # add label for y axis
            labs(colour = "Compartment") + # add legend title
            ggtitle(
                sprintf(
                    "Numbers of %s in %s vaccination doses",
                    index_map[index], vaccination
                )
            ) + # add title
            theme(plot.title = element_text(hjust = 0.5))

        plot_list[[cnt]] <- plot_temp
        cnt <- cnt + 1
    }
}

for (p in plot_list) {
    print(p)
}
```

